"""initial_schema

Revision ID: 780c678c3200
Revises: 
Create Date: 2026-04-05 14:31:11.169560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780c678c3200'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('subtopic', sa.String(length=100), nullable=True),
    sa.Column('prerequisite_topic_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_curriculum_difficulty'),
    sa.ForeignKeyConstraint(['prerequisite_topic_id'], ['curriculum_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade BETWEEN 1 AND 5', name='ck_students_grade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mastery_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('subtopic', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score BETWEEN 0.0 AND 1.0', name='ck_mastery_score_range'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'grade', 'topic', 'subtopic', name='uq_mastery_student_topic')
    )
    op.create_index('idx_mastery_student', 'mastery_scores', ['student_id', 'grade', 'topic'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_turns', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_student', 'sessions', ['student_id'], unique=False)
    op.create_table('session_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('emotion_label', sa.String(length=30), nullable=True),
    sa.Column('gaze_status', sa.String(length=20), nullable=True),
    sa.Column('agent_used', sa.String(length=50), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_session', 'session_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_session', table_name='session_events')
    op.drop_table('session_events')
    op.drop_index('idx_sessions_student', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_mastery_student', table_name='mastery_scores')
    op.drop_table('mastery_scores')
    op.drop_table('students')
    op.drop_table('curriculum_topics')
    # ### end Alembic commands ###
