"""Add streak and session metrics

Revision ID: bc11f2e73437
Revises: 5768394baee2
Create Date: 2026-04-25 22:10:04.378991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc11f2e73437'
down_revision: Union[str, Sequence[str], None] = '5768394baee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('performance_result', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('mastery_score', sa.SmallInteger(), nullable=True))
    op.add_column('students', sa.Column('streak', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'streak')
    op.drop_column('sessions', 'mastery_score')
    op.drop_column('sessions', 'performance_result')
    op.drop_column('sessions', 'duration_seconds')
    # ### end Alembic commands ###
